[phases.setup]
nixpkgs = ["pkgs.nodejs_20", "pkgs.npm"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[env]
NODE_VERSION = "20"
